[package]
name = "file-explorer"
edition = "2021"
version = "0.1.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", workspace = true, features = ["desktop"] }
printpdf = "0.3.1"
rfd = "0.15.3"
pulldown-cmark = "0.9"
tempfile = "3.20.0"
dioxus-router = "0.6.3"
chrono = "0.4.41"
open = "3.2.0" 

[workspace]

[workspace.dependencies]
dioxus = "0.6"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

